# Dev config only
version: '3.7'

services:
  web_app:
    image: tomcat:9.0-alpine
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tomcat
    ports:
      - 8080:8080
    volumes:
      - ./src/myApp:/usr/local/tomcat/webapps/myApp
